apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: my-container
        image: shoshan002/project2nd
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-registry-key


